apiVersion: v1
kind: ConfigMap
metadata:
  name: seemas-website-config
  namespace: prod
data:
  #Only public info that is needed can be added here
  ENVIRONMENT: "prod"
  AWS_REGION: "us-east-1"

  RDS_DBNAME: "website_prod"
  BASE_URL: "https://web.seemas.io"
  #This should be unique channel for each app. channel is 0-15, can beed increased from AWS
  REDIS_CACHE_LOCATION: "redis://main-redis.y7btrj.0001.use1.cache.amazonaws.com:6379/0"

  #----Assume the following are in cluster---#
  #"DOCDB_PASSWORD",
  #"DOCDB_USER",
  #"OPENAI_API_KEY",
  #"OPENAI_API_KEY_REPORT",
  #"OPENSEARCH_HOST",
  #"OPENSEARCH_PASSWORD",
  #"OPENSEARCH_PORT",
  #"OPENSEARCH_USER",
  #"RDS_HOSTNAME",
  #"RDS_PASSWORD",
  #"RDS_PORT",
  #"RDS_USERNAME"
